<?php

namespace WakeOnWeb\SalesforceClient\Model;

/**
 * Interface AccountMappingConstantsInterface
 */
interface AccountMappingConstantsInterface
{
    /**
     * @var int Salesforce relations with thecamp list mapping
     */
    // const TYPE_OF_RELATIONSHIP_BUSINESS = 2;
    // const TYPE_OF_RELATIONSHIP_BUYER    = 1;
    CONST RELATION_WITH_THECAMP_FOUNDING_PARTNER          = 1;
    CONST RELATION_WITH_THECAMP_BUSINESS                  = 2;
    CONST RELATION_WITH_THECAMP_PUBLIC_RELATIONSHIP_MEDIA = 3;
    CONST RELATION_WITH_THECAMP_CO_DESIGNER               = 4;
    CONST RELATION_WITH_THECAMP_LOCAL_ECOSYSTEM           = 5;
    CONST RELATION_WITH_THECAMP_DIGITIAL_ECOSYSTEM        = 6;
    CONST RELATION_WITH_THECAMP_BUILDING_SITE             = 7;
    CONST RELATION_WITH_THECAMP_PROVIDER                  = 8;
    CONST RELATION_WITH_THECAMP_ACCELERATED               = 9;
    CONST RELATION_WITH_THECAMP_PROSPECT_PARTNER          = 10;
    CONST RELATION_WITH_THECAMP_PROSPECT_PROVIDER         = 11;
    CONST RELATION_WITH_THECAMP_GOVERNING                 = 12;
    CONST RELATION_WITH_THECAMP_PROSPECT_EXPERIMENTATION  = 13;
    CONST RELATION_WITH_THECAMP_OTHERS                    = 14;
    CONST RELATION_WITH_THECAMP_NEW_PARTNER               = 15;
    CONST RELATION_WITH_THECAMP_KNOWLEDGE_PARTNER         = 16;
    CONST RELATION_WITH_THECAMP_FOUNDATION_RELATIONSHIP   = 17;
}