<?php

namespace WakeOnWeb\SalesforceClient\Model;

/**
 * Interface ContactMappingConstantsInterface
 *
 * Represent a Salesforce object
 */
interface ContactMappingConstantsInterface
{
    /**
     * @var string Salesforce salutation mapping
     */
    CONST SALUTATION_MR  = 'Mr.';
    CONST SALUTATION_MRS = 'Mrs.';
    // CONST SALUTATION_OTHER = 'other';

    /**
     * @var string Salesforce preferred email mapping
     */
    CONST PREFERRED_EMAIL_WORK      = 'Work';
    CONST PREFERRED_EMAIL_PERSONAL  = 'Personal';
    CONST PREFERRED_EMAIL_ALTERNATE = 'Alternate';

    /**
     * @var string Salesforce preferred phone mapping
     * @deprecated
     */
    // CONST PREFERRED_PHONE_WORK = 'Work';
    // CONST PREFERRED_PHONE_HOME = 'Home';

    /**
     * @var int Salesforce origin of member mapping
     */
    const ORIGIN_OF_MEMBER_SUBSCRIPTION = 2;

    /**
     * @var int Salesforce relations with thecamp list mapping
     */
    CONST RELATION_WITH_THECAMP_NO_RELATION                     = 0;
    CONST RELATION_WITH_THECAMP_AMBASSADOR                      = 4;
    CONST RELATION_WITH_THECAMP_CERCLE_1                        = 5;
    CONST RELATION_WITH_THECAMP_COPIL                           = 6;
    CONST RELATION_WITH_THECAMP_ATTENDEE                        = 7; //Participant
    CONST RELATION_WITH_THECAMP_ALUMNI                          = 8;
    CONST RELATION_WITH_THECAMP_EXTERNAL_CONTRACTOR             = 9;
    CONST RELATION_WITH_THECAMP_EXPERT                          = 10;
    CONST RELATION_WITH_THECAMP_TEENAGER_PARTICIPANT            = 11;
    CONST RELATION_WITH_THECAMP_STAFF                           = 12;
    CONST RELATION_WITH_THECAMP_BUYER                           = 13; //Business relationship
    CONST RELATION_WITH_THECAMP_CONTACT_ORGANIZATION            = 14;
    CONST RELATION_WITH_THECAMP_PUBLIC_RELATIONSHIP_MEDIA       = 15;
    CONST RELATION_WITH_THECAMP_INFLUENCER                      = 17;
    CONST RELATION_WITH_THECAMP_LEGAL_REPRESENTATION_OF_CHILD   = 18;
    CONST RELATION_WITH_THECAMP_CANDIDATE_NOT_SELECTED          = 19;
    CONST RELATION_WITH_THECAMP_TEENAGER_CANDIDATE_NOT_SELECTED = 20;
    CONST RELATION_WITH_THECAMP_VISITOR                         = 21;
    CONST RELATION_WITH_THECAMP_TEENAGE_EXTERNAL_CONTRIBUTOR    = 22;
    CONST RELATION_WITH_THECAMP_OTHER                           = 23;
    CONST RELATION_WITH_THECAMP_RECRUITEMENT_IN_PROGRESS        = 24;
    CONST RELATION_WITH_THECAMP_UNKNOWN                         = 25;
    CONST RELATION_WITH_THECAMP_HIVER                           = 26;
    CONST RELATION_WITH_THECAMP_PROSPECT_ADVISORY_BOARD         = 27;
    CONST RELATION_WITH_THECAMP_FRIEND                          = 28;
    CONST RELATION_WITH_THECAMP_FOUNDATION_RELATIONSHIP         = 29;

    /**
     * @var array Salesforce interests list mapping
     */
    CONST INTERESTS_LIST = [
        1  => 'Big Data',
        4  => 'Fintech',
        5  => 'Inclusive Design',
        6  => 'Design Fiction',
        7  => 'Design Thinking',
        8  => 'Artificial Intelligence',
        9  => 'Biomimicry',
        10 => 'Circular Economy',
        11 => 'Smart Cities',
        12 => 'Space',
        13 => 'Energies',
        14 => 'Democraty & Civic Rights',
        15 => 'Geopolitics',
        16 => 'Mobility',
        17 => 'Equality',
        18 => 'Education',
        19 => 'Biotechnology',
        20 => 'Food',
        21 => 'Environment',
        22 => 'Oceans',
        23 => 'Arts & Culture',
        26 => 'Virtual Reality',
        27 => 'Robotic',
        28 => 'Electronics',
        29 => 'Gamification',
        30 => 'Prospective',
        31 => 'Internet Of Things',
        32 => 'Blockchain',
        33 => 'Semantics',
        34 => 'Health',
    ];

    /**
     * @var array Salesforce nationalities list mapping
     */
    CONST NATIONALITIES_LIST = [
        1   => 'Afghan',
        2   => 'Central African',
        3   => 'Salvadoran',
        4   => 'Honduran',
        5   => 'Jamaican',
        6   => 'Malian',
        7   => 'Panamanian',
        8   => 'Serbian',
        9   => 'Turkish',
        10  => 'Algerian',
        11  => 'Belgian',
        12  => 'Bolivian',
        13  => 'Bosnian/Herzegovinian',
        14  => 'Brazilian',
        15  => 'British',
        16  => 'Bulgarian',
        17  => 'Cambodian',
        18  => 'Cameroonian',
        19  => 'Canadian',
        20  => 'Chadian',
        21  => 'Chinese',
        22  => 'Colombian',
        23  => 'Costa Rican',
        24  => 'Croatian',
        25  => 'Czech',
        26  => 'Congolese',
        27  => 'Danish',
        28  => 'Ecuadorian',
        29  => 'Egyptian',
        30  => 'English',
        31  => 'Estonian',
        32  => 'Ethiopian',
        33  => 'Finnish',
        34  => 'French',
        35  => 'German',
        36  => 'Ghanaian',
        37  => 'Greek',
        38  => 'Guatemalan',
        39  => 'Dutch',
        40  => 'Hungarian',
        41  => 'Icelandic',
        42  => 'Indian',
        43  => 'Indonesian',
        44  => 'Iranian',
        45  => 'Iraqi',
        46  => 'Irish',
        47  => 'Israeli',
        48  => 'Italian',
        49  => 'Ivorian',
        50  => 'Japanese',
        51  => 'Jordanian',
        52  => 'Kazakh',
        53  => 'Kenyan',
        54  => 'Lao',
        55  => 'Latvian',
        56  => 'Libyan',
        57  => 'Lithuanian',
        58  => 'Malagasy',
        59  => 'Malaysian',
        60  => 'Mauritanian',
        61  => 'Mexican',
        62  => 'Moroccan',
        63  => 'Namibian',
        64  => 'Nicaraguan',
        66  => 'Negirian',
        67  => 'Norwegian',
        68  => 'Omani',
        69  => 'Pakistani',
        70  => 'Paraguayan',
        71  => 'Peruvian',
        72  => 'Philippine',
        73  => 'Polish',
        74  => 'Portuguese',
        76  => 'Romanian',
        77  => 'Russian',
        78  => 'Saudi, Saudi Arabian',
        79  => 'Senegalese',
        80  => 'Slovak',
        81  => 'Somalian',
        82  => 'South African',
        83  => 'Spanish',
        84  => 'Sudanese',
        85  => 'Swedish',
        86  => 'Swiss',
        87  => 'Syrian',
        88  => 'Thai',
        89  => 'Tunisian',
        90  => 'Turkmen',
        91  => 'Ukranian',
        92  => 'Emirati',
        93  => 'American',
        94  => 'Vietnamese',
        95  => 'Welsh',
        96  => 'Zambian',
        97  => 'Zimbabwean',
        100 => 'Angolan',
        101 => 'Argentine',
        102 => 'Austrian',
        103 => 'Australian',
        104 => 'Bangladeshi',
        105 => 'Belarusian',
    ];

    /**
     * @var array Salesforce languages list mapping
     */
    CONST PREFERRED_LANGUAGES_LIST = [
        'FR',
        'EN',
    ];

    /**
     * @var array Salesforce languages list mapping
     */
    CONST LANGUAGES_LIST = [
        13 => 'French',
        8  => 'English',
        1  => 'Amharic',
        2  => 'Arabic',
        3  => 'Cambodian',
        4  => 'Chinese',
        5  => 'Creole',
        6  => 'Danish',
        7  => 'Dutch',
        9  => 'Estonian',
        10 => 'Filipino',
        11 => 'Finnish',
        12 => 'Flemish',
        14 => 'German',
        15 => 'Greek',
        16 => 'Hebrew',
        17 => 'Indonesian',
        18 => 'Irish',
        19 => 'Italian',
        20 => 'Japanese',
        21 => 'Korean',
        22 => 'Laotian',
        23 => 'Latvian',
        24 => 'Lithuanian',
        25 => 'Malaysian',
        26 => 'Maori',
        27 => 'Norwegian',
        28 => 'Persian',
        29 => 'Polish',
        30 => 'Portuguese',
        31 => 'Romanian',
        32 => 'Romansh',
        33 => 'Russian',
        34 => 'Spanish',
        35 => 'Swahili',
        36 => 'Swedish',
        37 => 'Tajik (Persia)',
        38 => 'Thai',
        39 => 'Turkish',
        40 => 'Ukrainian',
        41 => 'Vietnamese',
        42 => 'Welsh',
    ];

    /**
     * @var array Salesforce mailing country codes list mapping
     */
    CONST MAILING_COUNTRY_CODES_LIST = [
        'AF' => 'Afghanistan',
        'AX' => 'Aland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua and Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia, Plurinational State of',
        'BQ' => 'Bonaire, Sint Eustatius and Saba',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BV' => 'Bouvet Island',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'BN' => 'Brunei Darussalam',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'CV' => 'Cape Verde',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo',
        'CD' => 'Congo, the Democratic Republic of the',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Cote d\'Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands (Malvinas)',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HM' => 'Heard Island and McDonald Islands',
        'VA' => 'Holy See (Vatican City State)',
        'HN' => 'Honduras',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran, Islamic Republic of',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KP' => 'Korea, Democratic People\'s Republic of',
        'KR' => 'Korea, Republic of',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Lao People\'s Democratic Republic',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macao',
        'MK' => 'Macedonia, the former Yugoslav Republic of',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'MD' => 'Moldova, Republic of',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PS' => 'Palestine',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'QA' => 'Qatar',
        'RE' => 'Reunion',
        'RO' => 'Romania',
        'RU' => 'Russian Federation',
        'RW' => 'Rwanda',
        'BL' => 'Saint Barthélemy',
        'SH' => 'Saint Helena, Ascension and Tristan da Cunha',
        'KN' => 'Saint Kitts and Nevis',
        'LC' => 'Saint Lucia',
        'MF' => 'Saint Martin (French part)',
        'PM' => 'Saint Pierre and Miquelon',
        'VC' => 'Saint Vincent and the Grenadines',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Sao Tome and Principe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten (Dutch part)',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia and the South Sandwich Islands',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard and Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syrian Arab Republic',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania, United Republic of',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad and Tobago',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks and Caicos Islands',
        'TV' => 'Tuvalu',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VE' => 'Venezuela, Bolivarian Republic of',
        'VN' => 'Vietnam',
        'VG' => 'Virgin Islands, British',
        'WF' => 'Wallis and Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe',
    ];

    /**
     * @var array Salesforce phone country codes list mapping
     */
    CONST PHONE_COUNTRY_CODES = [
        '1'   => '+33', //FR
        '2'   => '+1', //US
        '3'   => '+247', //AC
        '4'   => '+376', //AD
        '5'   => '+971', //AE
        '6'   => '+93', //AF
        '7'   => '+355', //AL
        '8'   => '+374', //AM
        '9'   => '+244', //AO
        '10'  => '+54', //AR
        '11'  => '+43', //AT
        '12'  => '+61', //AU/CC/CX
        '13'  => '+297', //AW
        '14'  => '+994', //AZ
        '15'  => '+387', //BA
        '16'  => '+880', //BD
        '17'  => '+32', //BE
        '18'  => '+226', //BF
        '19'  => '+359', //BG
        '20'  => '+973', //BH
        '21'  => '+257', //BI
        '22'  => '+229', //BJ
        '23'  => '+673', //BN
        '24'  => '+591', //BO
        '25'  => '+55', //BR
        '26'  => '+975', //BT
        '27'  => '+267', //BW
        '28'  => '+375', //BY
        '29'  => '+501', //BZ
        '30'  => '+243', //CD
        '31'  => '+236', //CF
        '32'  => '+242', //CG
        '33'  => '+41', //CH
        '34'  => '+225', //CI
        '35'  => '+682', //CK
        '36'  => '+56', //CL
        '37'  => '+237', //CM
        '38'  => '+86', //CN
        '39'  => '+57', //CO
        '40'  => '+506', //CR
        '41'  => '+53', //CU
        '42'  => '+238', //CV
        '43'  => '+599', //CW/BQ
        '44'  => '+357', //CY
        '45'  => '+420', //CZ
        '46'  => '+49', //DE
        '47'  => '+253', //DJ
        '48'  => '+45', //DK
        '49'  => '+213', //DZ
        '50'  => '+593', //EC
        '51'  => '+372', //EE
        '52'  => '+20', //EG
        '53'  => '+291', //ER
        '54'  => '+34', //ES
        '55'  => '+251', //ET
        '56'  => '+358', //FI/AX
        '57'  => '+679', //FJ
        '58'  => '+500', //FK
        '59'  => '+691', //FM
        '60'  => '+298', //FO
        '61'  => '+241', //GA
        '62'  => '+44', //GB/GG/IM/JE
        '63'  => '+995', //GE
        '64'  => '+594', //GF
        '65'  => '+233', //GH
        '66'  => '+350', //GI
        '67'  => '+299', //GL
        '68'  => '+220', //GM
        '69'  => '+224', //GN
        '70'  => '+590', //PBL/MF
        '71'  => '+240', //GQ
        '72'  => '+30', //GR
        '73'  => '+502', //GT
        '74'  => '+245', //GW
        '75'  => '+592', //GY
        '76'  => '+852', //HK
        '77'  => '+504', //HN
        '78'  => '+385', //HR
        '79'  => '+509', //HT
        '80'  => '+36', //HU
        '81'  => '+62', //ID
        '82'  => '+353', //IE
        '83'  => '+972', //IL
        '84'  => '+91', //IN
        '85'  => '+246', //IO
        '86'  => '+964', //IQ
        '87'  => '+98', //IR
        '88'  => '+354', //IS
        '89'  => '+39', //IT/VA
        '90'  => '+962', //JO
        '91'  => '+81', //JP
        '92'  => '+254', //KE
        '93'  => '+996', //KG
        '94'  => '+855', //KH
        '95'  => '+686', //KI
        '96'  => '+269', //KM
        '97'  => '+850', //KP
        '98'  => '+82', //KR
        '99'  => '+965', //KW
        '100' => '+856', //LA
        '101' => '+961', //LB
        '102' => '+423', //LI
        '103' => '+94', //LK
        '104' => '+231', //LR
        '105' => '+266', //LS
        '106' => '+370', //LT
        '107' => '+352', //LU
        '108' => '+371', //LV
        '109' => '+218', //LY
        '110' => '+212', //MA/EH
        '111' => '+377', //MC
        '112' => '+373', //MD
        '113' => '+382', //ME
        '114' => '+261', //MG
        '115' => '+692', //MH
        '116' => '+389', //MK
        '117' => '+223', //ML
        '118' => '+95', //MM
        '119' => '+976', //MN
        '120' => '+853', //MO
        '121' => '+596', //MQ
        '122' => '+222', //MR
        '123' => '+356', //MT
        '124' => '+230', //MU
        '125' => '+960', //MV
        '126' => '+265', //MW
        '127' => '+52', //MX
        '128' => '+60', //MY
        '129' => '+258', //MZ
        '130' => '+264', //NA
        '131' => '+687', //NC
        '132' => '+227', //NE
        '133' => '+672', //NF
        '134' => '+234', //NG
        '135' => '+505', //NI
        '136' => '+31', //NL
        '137' => '+47', //NO/SJ
        '138' => '+977', //NP
        '139' => '+674', //NR
        '140' => '+683', //NU
        '141' => '+64', //NZ
        '142' => '+968', //OM
        '143' => '+507', //PA
        '144' => '+51', //PE
        '145' => '+689', //PF
        '146' => '+675', //PG
        '147' => '+63', //PH
        '148' => '+92', //PK
        '149' => '+48', //PL
        '150' => '+508', //PM
        '151' => '+970', //PS
        '152' => '+351', //PT
        '153' => '+680', //PW
        '154' => '+595', //PY
        '155' => '+974', //QA
        '156' => '+262', //RE/YT
        '157' => '+40', //RO
        '158' => '+381', //RS
        '159' => '+7', //RU/KZ
        '160' => '+250', //RW
        '161' => '+966', //SA
        '162' => '+677', //SB
        '163' => '+248', //SC
        '164' => '+249', //SD
        '165' => '+46', //SE
        '166' => '+65', //SG
        '167' => '+290', //SH/TA
        '168' => '+386', //SI
        '169' => '+421', //SK
        '170' => '+232', //SL
        '171' => '+378', //SM
        '172' => '+221', //SN
        '173' => '+252', //SO
        '174' => '+597', //SR
        '175' => '+211', //SS
        '176' => '+963', //SY
        '177' => '+268', //SZ
        '178' => '+235', //TD
        '179' => '+228', //TG
        '180' => '+66', //TH
        '181' => '+670', //TL
        '182' => '+90', //TR
        '183' => '+886', //TW
        '184' => '+255', //TZ
        '185' => '+380', //UA
        '186' => '+256', //UG
        '187' => '+598', //UY
        '188' => '+998', //UZ
        '189' => '+58', //VE
        '190' => '+84', //VN
        '191' => '+678', //VU
        '192' => '+681', //WF
        '193' => '+685', //WS
        '194' => '+967', //YE
        '195' => '+27', //ZA
        '196' => '+260', //ZM
        '197' => '+263', //ZW
        '198' => '+216', //TN
        '199' => '+239', //ST
        '200' => '+503', //SV
        '202' => '+688', //TV
        '201' => '+676', //TO
        '203' => '+690', //TK
        '204' => '+992', //TJ
        '205' => '+993', //TM
    ];
}
